### PR TITLE
If not recording audio we sync the video against a 'system clock' (cf…

### PR DESCRIPTION
**Pull request by smallfly**
… issue #13). Also added start() and setPaused() methods to be able to handle pauses while recording a video (vs the 'system clock'). Updated the example to show the uses of these 2 new methods.

### CODE REVIEW

**Comment by smallfly** [comment]
Good ideas. I will update the PR later today.

**Comment by smallfly** [comment]
The PR has been updated. Let me know if anything else need to be done.

**Comment by timscaffidi** [comment]
Great this is exactly what I was envisioning. The only issue now is that there is a lot of trailing whitespace on several of the spacing lines that you added. As in, there are a bunch of lines that match the indentation of the previous / next line of code, but there is no code on the line.

**Comment by timscaffidi** [comment]
Some text editors (sublime text for example) have an option to trim trailing white space on save that should take care of this all in one go.

**Comment by smallfly** [comment]
Done.

**Pull request merged**
