### PR TITLE
We can now set ffmpeg log to silent via a bool arg in the setup methods.

### PR DESCRIPTION
**Pull request by smallfly**

### CODE REVIEW

**Comment by smallfly** [comment]
I have made an error. Two commits that are not linked in the same PR. I'm closing this PR and will submit two proper PRs.

**Comment by timscaffidi** [comment]
Cool, thanks @smallfly! I will look into merging these as soon as I can.

**Comment by smallfly** [comment]
Great. I will most likely have a couple of other PRs coming your way soon. Is there a way you would like me to proceed in order to simplify your review (and possible merge) process?

**Comment by timscaffidi** [comment]
Nope. your PRs merged in cleanly. Thanks a bunch for contributing!

**Pull request closed without merging**
